### ISSUE TITLE
SimpleTiledWFC doesn't generate anything

### ISSUE THREAD

**Issue by leo-petrucci** [selfsame/unity-wave-function-collapse#10]
I'm having some trouble getting this to work.

My XML file is generating just fine (https://pastebin.com/8yQQbyKa), however nothing happens if I press generate (or RUN).

Here's a video of me trying to generate from tiles.
https://youtu.be/NRF8oz0E3pg

I also zipped up the project and uploaded it to drive if that helps.

I don't think I'm doing anything wrong, the simple example works just fine. I tried the scripts both before and after running Unity's automatic API update system but the result is the same in both cases.

Very sorry to bother with this since it's probably my fault, but please let me know if I'm doing something wrong.

**Comment by selfsame** [comment]
@lovemoebius hmm hard to see that video, can you give me the link to the project zip and tell me what version of unity & unity-wave-function-collapse you're on?

**Comment by selfsame** [comment]
Also - were there any errors in the console?

**Comment by leo-petrucci** [comment]
I can't believe I forgot to link the zip after uploading https://drive.google.com/open?id=12lNi_LRMW8VcLsVxoit6b3cPwAW5y650

Also no, no errors.

**Comment by leo-petrucci** [comment]
After doing some Debug Logging, the Draw function seems to run fine, but when it has to check 
`if (v != "?")`
it results in a false result and (I think) it fails to draw any of the tiles.

`model.Sample(x, y)`
Results in "?"

` fab = (GameObject)Resources.Load(v, typeof(GameObject));`
This seems to run only twice

**Comment by selfsame** [comment]
@lovemoebius ah looks like some of the API has changed with 2018, will see if I can sort it out

**Comment by leo-petrucci** [comment]
@selfsame Which version of Unity was this last tested on?

**Comment by selfsame** [comment]
@lovemoebius the stable 2017 release i think, also think the github repo is behind https://notabug.org/selfsame/unity-wave-function-collapse

**Comment by selfsame** [comment]
@lovemoebius so I think the problem was the prefabs need to be somewhere inside a `Resources` directory (so that they can be instantiated by their path name).

I was able to get it to work in 2018.2.0f2 with the automatic api updates:

![image](https://user-images.githubusercontent.com/2467644/42963272-bea61978-8b61-11e8-849e-628958a23b77.png)

**Comment by leo-petrucci** [comment]
It does look like it's running, but I don't think it's doing so properly.

I'll try to run it on an older unity version and see if the results are different.

https://youtu.be/n_icN1zqO-w

**Comment by selfsame** [comment]
@lovemoebius yeah you'll have to give the triangle a different symmetry, which you do with the prefab name.  Try `triangleL`?

From the readme, the options are:

`X I T L`

Tile symmetry class can be declared via the last letter of the prefab name, for example "GroundX" or "Road-T".

I think the default is X if there's no symmetry letter at the end.

**Comment by leo-petrucci** [comment]
Ah I see, it's working now.

This is some pretty amazing stuff right here, thank you for porting it to unity. I'll go read the original release to get more info about the tile script.

**Comment by leo-petrucci** [comment]
I hate to post again and bother, but I cannot get anything that looks right by using the TiledWFC. 
I looked into the code to understand better how it works, but without any comments I didn't get very far.

I'm unsure if I'm just using it wrong or I just don't understand how the symmetries work, but I can't seem to be able to generate even a simple level.

Correct me if I'm wrong, but these are what the symmetries mean:
>X can be flipped on both axes
>T can be flipped on the X axis
>I can be flipped on the Y axis

Where the problem comes in is with L. 

> Note: `L` tiles have an initial orientation of

    OO
    OX

No matter what orientation I put my tile in, it just refuses to work.
Is this how it's supposed to be oriented or is it the other way around?

![symmetry](https://i.imgur.com/jrOiHT7.png)
![symmetry2](https://i.imgur.com/M3TSqVF.png)

Should these two corners have symmetry L? What does symmetry L actually mean?

I've also noticed the code has a definition for "Symmetry D", what is that exactly?

**Comment by selfsame** [comment]
@lovemoebius no worries, the Tiled Model is pretty hard to understand at first.

The Tiled Model is based on rules for legal edge connections, the symmetries are a way to simplify those rules for tiles where some eges share legal connections, you only have to provide one example and the symmetrical rules are generated

`X` means all sides are the same, so if a `grassX` and `sandX` have a rule, it duplicates that for every side.
`I` means opposing sides share rules, top+bottom and left+right (imagine a straight section of road)
`T` i think is like X except for the top side.
`L` means the top+left and bottom+right are shared.
`D` is the diagonal `\` rule from https://github.com/mxgmn/WaveFunctionCollapse#tilemap-generation. I never really found a use for it so ommitted it from the readme but I should make a note about it.

Here's a screenshot of the minimal training for a `solid-X` and `diagonal-L`

![image](https://user-images.githubusercontent.com/2467644/43049661-30c1112a-8dc9-11e8-8a03-aa4e898bc352.png)

Looking at your screenshots - i kind of think those might not be suitable for a symmetry rule? Because of the wall edge there's specific orientations they can neighbor.  If that's the case you'd have to provide training with examples for every side of them.

Also there's no harm in providing more training data than needed for the Tiled Model, `record neighbors` only adds unique connections that it hasn't seen before.

Let me know if that helps!

**Comment by leo-petrucci** [comment]
That was extremely helpful! The problem was with the corner tiles, there's apparently very specific ways to make them compatible with all the other tiles, if that step is skipped what comes out will most likely not make sense at all.

I was referenced to this guide that uses the tiles from the guide's examples on Reddit and it helped a lot with comprehension. I'll leave it here for future reference in case anyone else is confused.

![image](https://i.imgur.com/LPb6Vvn.png)
